/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cvg.sfmPipeline.calibration;

public class CalibrationJNI {
  public final static native void MutualCalibration_rotationTest_set(long jarg1, MutualCalibration jarg1_, long jarg2);
  public final static native long MutualCalibration_rotationTest_get(long jarg1, MutualCalibration jarg1_);
  public final static native void MutualCalibration_pRotationTest_set(long jarg1, MutualCalibration jarg1_, long jarg2);
  public final static native long MutualCalibration_pRotationTest_get(long jarg1, MutualCalibration jarg1_);
  public final static native long new_MutualCalibration__SWIG_0(long jarg1, long jarg2, long jarg3, long jarg4, boolean jarg5, boolean jarg6);
  public final static native long new_MutualCalibration__SWIG_1(long jarg1, long jarg2, long jarg3, long jarg4, boolean jarg5);
  public final static native long new_MutualCalibration__SWIG_2(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native boolean MutualCalibration_tryAddingChessboardImage(long jarg1, MutualCalibration jarg1_, long jarg2, long jarg3);
  public final static native void MutualCalibration_addIMUData(long jarg1, MutualCalibration jarg1_, double jarg2, double jarg3, double jarg4);
  public final static native long MutualCalibration_getNumberOfImages(long jarg1, MutualCalibration jarg1_);
  public final static native void MutualCalibration_calibrateCamera(long jarg1, MutualCalibration jarg1_);
  public final static native void MutualCalibration_mutualCalibrate(long jarg1, MutualCalibration jarg1_);
  public final static native void delete_MutualCalibration(long jarg1);
}
