/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cvg.sfmPipeline.calibration;

public class MutualCalibration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public MutualCalibration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MutualCalibration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CalibrationJNI.delete_MutualCalibration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MutualCalibration(long heightImage, long widthImage, long heightBoard, long widthBoard, boolean useOpenCVCorner, boolean useOnlyIMUGravity, boolean useRANSAC) {
    this(CalibrationJNI.new_MutualCalibration__SWIG_0(heightImage, widthImage, heightBoard, widthBoard, useOpenCVCorner, useOnlyIMUGravity, useRANSAC), true);
  }

  public MutualCalibration(long heightImage, long widthImage, long heightBoard, long widthBoard, boolean useOpenCVCorner, boolean useOnlyIMUGravity) {
    this(CalibrationJNI.new_MutualCalibration__SWIG_1(heightImage, widthImage, heightBoard, widthBoard, useOpenCVCorner, useOnlyIMUGravity), true);
  }

  public MutualCalibration(long heightImage, long widthImage, long heightBoard, long widthBoard, boolean useOpenCVCorner) {
    this(CalibrationJNI.new_MutualCalibration__SWIG_2(heightImage, widthImage, heightBoard, widthBoard, useOpenCVCorner), true);
  }

  public MutualCalibration(long heightImage, long widthImage, long heightBoard, long widthBoard) {
    this(CalibrationJNI.new_MutualCalibration__SWIG_3(heightImage, widthImage, heightBoard, widthBoard), true);
  }

  public boolean tryAddingChessboardImage(long inputImage, long outputImage) {
    return CalibrationJNI.MutualCalibration_tryAddingChessboardImage(swigCPtr, this, (inputImage), (outputImage));
  }

  public boolean tryAddingVanishingPointImage(long inputImage, long outputImage) {
    return CalibrationJNI.MutualCalibration_tryAddingVanishingPointImage(swigCPtr, this, (inputImage), (outputImage));
  }

  public void addFullIMURotationByQuaternion(double r0, double r1, double r2) {
    CalibrationJNI.MutualCalibration_addFullIMURotationByQuaternion(swigCPtr, this, r0, r1, r2);
  }

  public void addIMUGravityVector(double g1, double g2, double g3) {
    CalibrationJNI.MutualCalibration_addIMUGravityVector(swigCPtr, this, g1, g2, g3);
  }

  public long getNumberOfImages() {
    return CalibrationJNI.MutualCalibration_getNumberOfImages(swigCPtr, this);
  }

  public void getRotationMatrix(double[] p) {
    CalibrationJNI.MutualCalibration_getRotationMatrix(swigCPtr, this, p);
  }

  public void getCameraMatrix(double[] p) {
    CalibrationJNI.MutualCalibration_getCameraMatrix(swigCPtr, this, p);
  }

  public void calibrateCamera() {
    CalibrationJNI.MutualCalibration_calibrateCamera(swigCPtr, this);
  }

  public boolean mutualCalibrate() {
    return CalibrationJNI.MutualCalibration_mutualCalibrate(swigCPtr, this);
  }

}
